
### Login admin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "cpf": "11111111111",
    "senha": "admin"
}

### Token de autenticação
@authToken = <o token>


### Registrar aluno
POST http://localhost:3000/auth/cadastro
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "nome": "Usuario de testes",
    "cpf": "896.210.900-08",
    "senha": "aluno123",
    "funcao": "aluno"
}

### Login aluno
POST http://localhost:3000/auth/login
Content-Type: application/json
{
    "cpf": "12345678901",
    "senha": "password123"
}

### Login funcionario
POST http://localhost:3000/auth/login
Content-Type: application/json
{
    "cpf": "12345678902",
    "senha": "password123"
}

### listar todos os usuarios
GET http://localhost:3000/usuario
Authorization: Bearer {{authToken}}

### criar um veiculo novo para o usuario
POST http://localhost:3000/veiculo
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "placa": "ACC1234"
}

### listar os veiculos de todos os usuarios
GET http://localhost:3000/veiculo/todos
Authorization: Bearer {{authToken}}

### listar os veiculos que o usuario logado tem
GET http://localhost:3000/veiculo
Authorization: Bearer {{authToken}}


### criar um relatorio de entrada
POST http://localhost:3000/relatorio/entrada
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "veiculo_id": 1
}

### ver todos os relatorios
GET http://localhost:3000/relatorio/todos
Authorization: Bearer {{authToken}}

### listar todos os relatorios que os veiculos do usuario tem
GET http://localhost:3000/relatorio
Authorization: Bearer {{authToken}}

### registrar uma saida de veiculo
PUT http://localhost:3000/relatorio/saida/1
Authorization: Bearer {{authToken}}

### status do estacionamento e quantidade de vagas
GET http://localhost:3000/estacionamento
Authorization: Bearer {{authToken}}
### Delete a vehicle by ID
DELETE http://localhost:3000/veiculo/3
Authorization: Bearer {{authToken}}

### Update vehicle information
PUT http://localhost:3000/veiculo/4
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "placa": "XYZ5678",
    "donoId": 1
}

### Get vehicle details by ID
GET http://localhost:3000/veiculo/1
Authorization: Bearer {{authToken}}

### Delete a report by ID
DELETE http://localhost:3000/relatorio/3
Authorization: Bearer {{authToken}}

### Update report information
PUT http://localhost:3000/relatorio/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "veiculo_id": 2,
    "saida": "2023-10-01T12:00:00Z"
}

### Get report details by ID
GET http://localhost:3000/relatorio/1
Authorization: Bearer {{authToken}}